CREATE TABLE COUNTRIES_MASTER (
    CNT_ID INTEGER AUTO_INCREMENT,
    CNT_NAME VARCHAR(100) NOT NULL,
    CNT_FULL_NAME VARCHAR(200) NOT NULL,
    CNT_DESC VARCHAR(100),
    CNT_NLTY VARCHAR(50) NOT NULL,
    PRIMARY KEY (CNT_ID)
);


CREATE TABLE FORIGNEMBASSYMASTER (
    EMBASSYID INTEGER AUTO_INCREMENT,
    COUNTRYID INTEGER NOT NULL,
    EMBASSYNAME VARCHAR(100) NOT NULL,
    EMBASSYADDRESS VARCHAR(200),
    EMBASSYCONTACTPERNAME VARCHAR(30),
    EMBASSYPHONENO VARCHAR(20),
    PRIMARY KEY (EMBASSYID),
    CONSTRAINT EMBY_COUNTRY_ID_UK UNIQUE (EMBASSYID)
);

   
CREATE TABLE DEPARTMENTMASTER (
    DEPARTMENTID INTEGER AUTO_INCREMENT,
    DEPARTMENTNAME VARCHAR(40),
    DEPARTMENTABBR VARCHAR(40),
    DEPARTMENTINCHGID INTEGER,
    PRIMARY KEY (DEPARTMENTID)
);

CREATE TABLE EMPLOYEEMASTER (
    EMPLOYEEID INTEGER AUTO_INCREMENT,
    FIRSTNAME VARCHAR(20),
    LASTNAME VARCHAR(20),
    DOB DATE,
    DOJ DATE,
    LOGINID VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(30),
    S_QUES VARCHAR(70),
    S_ANS VARCHAR(70),
    EMAIL VARCHAR(40),
    PHONE VARCHAR(20),
    PHOTO BLOB,
    DEPARTMENTID INTEGER,
    TYPE VARCHAR(20),
    PHOTOEXT VARCHAR(10),
    GENDER VARCHAR(10),
    PRIMARY KEY (EMPLOYEEID),
    CONSTRAINT EMPS_LOGINID_UK UNIQUE (LOGINID)
);

CREATE TABLE ADDRESSES (
    EMPLOYEEID INTEGER,
    ADDRESSID INTEGER AUTO_INCREMENT,
    ADDRESSTYPE VARCHAR(20),
    LINE1 VARCHAR(30),
    LINE2 VARCHAR(30),
    CITY VARCHAR(30),
    STATE VARCHAR(30),
    COUNTRY VARCHAR(30),
    PINCODE VARCHAR(10),
    PRIMARY KEY (ADDRESSID)
);

CREATE TABLE PASSPORTS (
    PPT_ID INTEGER AUTO_INCREMENT,
    EMP_PPT_FK INTEGER NOT NULL,
    CNT_PPT_FK INTEGER NOT NULL,
    PPT_TYPE VARCHAR(20) NOT NULL,
    PPT_NUMBER VARCHAR(20) NOT NULL,
    PPT_BIRTH_PLACE VARCHAR(50) NOT NULL,
    PPT_ISSUE_DATE DATE NOT NULL,
    PPT_EXPIRY_DATE DATE NOT NULL,
    PPT_ISSUE_PLACE VARCHAR(50) NOT NULL,
    PPT_ADDRESS VARCHAR(150) NOT NULL,
    PPT_COMMENTS VARCHAR(200),
    PRIMARY KEY (PPT_ID)
);

CREATE TABLE VISA_TYPES (
    VT_ID INTEGER AUTO_INCREMENT,
    CNT_VT_FK INTEGER NOT NULL,
    VT_NAME VARCHAR(50) NOT NULL,
    VT_ABBR VARCHAR(50) NOT NULL,
    VT_DESC VARCHAR(100),
    VT_ELEG VARCHAR(100),
    VT_STAY_MAX_DUR INTEGER,
    VT_STAMP_GUIDE VARCHAR(200),
    VT_REQUIRED_ADV TINYINT,
    PRIMARY KEY (VT_ID)
);

CREATE TABLE EMP_VISAS (
    EV_ID INTEGER AUTO_INCREMENT,
    PPT_EV_FK INTEGER NOT NULL,
    VT_EV_FK INTEGER,
    EV_NUMBER VARCHAR(20) NOT NULL,
    EV_ISSUE_DATE DATE NOT NULL,
    EV_EXPIRE_DATE DATE NOT NULL,
    EV_MAX_VISITS INTEGER NOT NULL,
    EV_VISIT_COUNT INTEGER,
    EV_PLACE_OF_ISSUE VARCHAR(50) NOT NULL,
    EV_COMMENTS VARCHAR(200),
    EV_CANCEL_STATUS TINYINT,
    EV_CANCEL_DATE DATE,
    EV_COST VARCHAR(20),
    PRIMARY KEY (EV_ID)
);

CREATE TABLE HOTELMASTER (
    HOTELID INTEGER AUTO_INCREMENT,
    HOTELNAME VARCHAR(30),
    HOTELADDR VARCHAR(50),
    HOTELPHONENO VARCHAR(30),
    HOTELCONTACTPERSONNAME VARCHAR(30),
    HOTELMINRENTALCHARGES INTEGER,
    HOTELMAXCHARGES INTEGER,
    COUNTRYID INTEGER,
    PRIMARY KEY (HOTELID)
);

CREATE TABLE TICKETSMASTER (
    TICKETID INTEGER AUTO_INCREMENT,
    TRAVELID INTEGER,
    TICKETNO VARCHAR(20),
    BOOKEDDATE DATE,
    AVAILABLEDATE DATE,
    TICKETFROM VARCHAR(30),
    TICKETTO VARCHAR(30),
    SEATNO VARCHAR(30),
    TRANSPORTERNAME VARCHAR(50),
    VEHICLETYPE VARCHAR(20),
    CUSTOMERCARE VARCHAR(20),
    JOURNEYTIME VARCHAR(15),
    VEHICLENO VARCHAR(15),
    PRIMARY KEY (TICKETID)
);

CREATE TABLE WORKS (
    WORK_ID INTEGER AUTO_INCREMENT,
    CNT_WORK_FK INTEGER,
    EMP_WORK_INCH_FK INTEGER,
    WORK_TITLE VARCHAR(200),
    WORK_RSPB VARCHAR(200),
    WORK_DESC VARCHAR(800),
    WORK_STATUS INTEGER,
    PRIMARY KEY (WORK_ID)
);

CREATE TABLE TRAVELMASTER (
    TRAVELID INTEGER AUTO_INCREMENT,
    EMPLOYEEID INTEGER,
    TRAVELSTARTDATE DATE,
    TRAVELENDDATE DATE,
    INSTRUCTIONS VARCHAR(200),
    WORKID INTEGER,
    PRIMARY KEY (TRAVELID)
);

CREATE TABLE EMPLOYEESSTAYMASTER (
    STAYID INTEGER AUTO_INCREMENT,
    TRAVELID INTEGER,
    HOTELID INTEGER,
    ROOMNO VARCHAR(10),
    PICKUPVEHICLENO VARCHAR(30),
    PRIMARY KEY (STAYID),
    CONSTRAINT EMST_TRAVEL_ID_UK UNIQUE (TRAVELID)
);