--------------------------------------------------------
--  File created - Monday-June-12-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESSES
--------------------------------------------------------

  CREATE TABLE "PROJ"."ADDRESSES" 
   (	"EMPLOYEEID" NUMBER, 
	"ADDRESSID" NUMBER, 
	"ADDRESSTYPE" VARCHAR2(20 BYTE), 
	"LINE1" VARCHAR2(30 BYTE), 
	"LINE2" VARCHAR2(30 BYTE), 
	"CITY" VARCHAR2(30 BYTE), 
	"STATE" VARCHAR2(30 BYTE), 
	"COUNTRY" VARCHAR2(30 BYTE), 
	"PINCODE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COUNTRIES_MASTER
--------------------------------------------------------

  CREATE TABLE "PROJ"."COUNTRIES_MASTER" 
   (	"CNT_ID" NUMBER, 
	"CNT_NAME" VARCHAR2(100 BYTE), 
	"CNT_FULL_NAME" VARCHAR2(200 BYTE), 
	"CNT_DESC" VARCHAR2(100 BYTE), 
	"CNT_NLTY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENTMASTER
--------------------------------------------------------

  CREATE TABLE "PROJ"."DEPARTMENTMASTER" 
   (	"DEPARTMENTID" NUMBER, 
	"DEPARTMENTNAME" VARCHAR2(40 BYTE), 
	"DEPARTMENTABBR" VARCHAR2(40 BYTE), 
	"DEPARTMENTINCHGID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEEMASTER
--------------------------------------------------------

  CREATE TABLE "PROJ"."EMPLOYEEMASTER" 
   (	"EMPLOYEEID" NUMBER, 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"DOB" DATE, 
	"DOJ" DATE, 
	"LOGINID" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"S_QUES" VARCHAR2(70 BYTE), 
	"S_ANS" VARCHAR2(70 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"PHOTO" BLOB, 
	"DEPARTMENTID" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"PHOTOEXT" VARCHAR2(10 BYTE), 
	"GENDER" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EMPLOYEESSTAYMASTER
--------------------------------------------------------

  CREATE TABLE "PROJ"."EMPLOYEESSTAYMASTER" 
   (	"STAYID" NUMBER, 
	"TRAVELID" NUMBER, 
	"HOTELID" NUMBER, 
	"ROOMNO" VARCHAR2(10 BYTE), 
	"PICKUPVEHICLENO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMP_VISAS
--------------------------------------------------------

  CREATE TABLE "PROJ"."EMP_VISAS" 
   (	"EV_ID" NUMBER, 
	"PPT_EV_FK" NUMBER, 
	"VT_EV_FK" NUMBER, 
	"EV_NUMBER" VARCHAR2(20 BYTE), 
	"EV_ISSUE_DATE" DATE, 
	"EV_EXPIRE_DATE" DATE, 
	"EV_MAX_VISITS" NUMBER, 
	"EV_VISIT_COUNT" NUMBER, 
	"EV_PLACE_OF_ISSUE" VARCHAR2(50 BYTE), 
	"EV_COMMENTS" VARCHAR2(200 BYTE), 
	"EV_CANCEL_STATUS" NUMBER(1,0), 
	"EV_CANCEL_DATE" DATE, 
	"EV_COST" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FORIGNEMBASSYMASTER
--------------------------------------------------------

  CREATE TABLE "PROJ"."FORIGNEMBASSYMASTER" 
   (	"EMBASSYID" NUMBER, 
	"COUNTRYID" NUMBER, 
	"EMBASSYNAME" VARCHAR2(100 BYTE), 
	"EMBASSYADDRESS" VARCHAR2(200 BYTE), 
	"EMBASSYCONTACTPERNAME" VARCHAR2(30 BYTE), 
	"EMBASSYPHONENO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOTELMASTER
--------------------------------------------------------

  CREATE TABLE "PROJ"."HOTELMASTER" 
   (	"HOTELID" NUMBER, 
	"HOTELNAME" VARCHAR2(30 BYTE), 
	"HOTELADDR" VARCHAR2(50 BYTE), 
	"HOTELPHONENO" VARCHAR2(30 BYTE), 
	"HOTELCONTACTPERSONNAME" VARCHAR2(30 BYTE), 
	"HOTELMINRENTALCHARGES" NUMBER, 
	"HOTELMAXCHARGES" NUMBER, 
	"COUNTRYID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PASSPORTS
--------------------------------------------------------

  CREATE TABLE "PROJ"."PASSPORTS" 
   (	"PPT_ID" NUMBER, 
	"EMP_PPT_FK" NUMBER, 
	"CNT_PPT_FK" NUMBER, 
	"PPT_TYPE" VARCHAR2(20 BYTE), 
	"PPT_NUMBER" VARCHAR2(20 BYTE), 
	"PPT_BIRTH_PLACE" VARCHAR2(50 BYTE), 
	"PPT_ISSUE_DATE" DATE, 
	"PPT_EXPIRY_DATE" DATE, 
	"PPT_ISSUE_PLACE" VARCHAR2(50 BYTE), 
	"PPT_ADDRESS" VARCHAR2(150 BYTE), 
	"PPT_COMMENTS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "PROJ"."TEST" 
   (	"D" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKETSMASTER
--------------------------------------------------------

  CREATE TABLE "PROJ"."TICKETSMASTER" 
   (	"TICKETID" NUMBER, 
	"TRAVELID" NUMBER, 
	"TICKETNO" VARCHAR2(20 BYTE), 
	"BOOKEDDATE" DATE, 
	"AVAILABLEDATE" DATE, 
	"TICKETFROM" VARCHAR2(30 BYTE), 
	"TICKETTO" VARCHAR2(30 BYTE), 
	"SEATNO" VARCHAR2(30 BYTE), 
	"TRANSPORTERNAME" VARCHAR2(50 BYTE), 
	"VEHICLETYPE" VARCHAR2(20 BYTE), 
	"CUSTOMERCARE" VARCHAR2(20 BYTE), 
	"JOURNEYTIME" VARCHAR2(15 BYTE), 
	"VEHICLENO" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRAVELMASTER
--------------------------------------------------------

  CREATE TABLE "PROJ"."TRAVELMASTER" 
   (	"TRAVELID" NUMBER, 
	"EMPLOYEEID" NUMBER, 
	"TRAVELSTARTDATE" DATE, 
	"TRAVELENDDATE" DATE, 
	"INSTRUCTIONS" VARCHAR2(200 BYTE), 
	"WORKID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VISA_TYPES
--------------------------------------------------------

  CREATE TABLE "PROJ"."VISA_TYPES" 
   (	"VT_ID" NUMBER, 
	"CNT_VT_FK" NUMBER, 
	"VT_NAME" VARCHAR2(50 BYTE), 
	"VT_ABBR" VARCHAR2(50 BYTE), 
	"VT_DESC" VARCHAR2(100 BYTE), 
	"VT_ELEG" VARCHAR2(100 BYTE), 
	"VT_STAY_MAX_DUR" NUMBER, 
	"VT_STAMP_GUIDE" VARCHAR2(200 BYTE), 
	"VT_REQUIRED_ADV" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WORKS
--------------------------------------------------------

  CREATE TABLE "PROJ"."WORKS" 
   (	"WORK_ID" NUMBER, 
	"CNT_WORK_FK" NUMBER, 
	"EMP_WORK_INCH_FK" NUMBER, 
	"WORK_TITLE" VARCHAR2(200 BYTE), 
	"WORK_RSPB" VARCHAR2(200 BYTE), 
	"WORK_DESC" VARCHAR2(800 CHAR), 
	"WORK_STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence ADDR_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJ"."ADDR_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CNT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJ"."CNT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEPT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJ"."DEPT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMBS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJ"."EMBS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMP_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJ"."EMP_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HOTEL_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJ"."HOTEL_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PPT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJ"."PPT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STAY_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJ"."STAY_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TICKET_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJ"."TICKET_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRAVEL_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJ"."TRAVEL_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VISA_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJ"."VISA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VTYPE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJ"."VTYPE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence WORK_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJ"."WORK_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000020 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Index CNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJ"."CNT_PK" ON "PROJ"."COUNTRIES_MASTER" ("CNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMP_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJ"."EMP_ID_PK" ON "PROJ"."EMPLOYEEMASTER" ("EMPLOYEEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EV_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJ"."EV_PK" ON "PROJ"."EMP_VISAS" ("EV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMP_STAY_TID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJ"."EMP_STAY_TID" ON "PROJ"."EMPLOYEESSTAYMASTER" ("TRAVELID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPT_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJ"."DEPT_ID_PK" ON "PROJ"."DEPARTMENTMASTER" ("DEPARTMENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJ"."VT_PK" ON "PROJ"."VISA_TYPES" ("VT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMBASSY_CID_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJ"."EMBASSY_CID_UK" ON "PROJ"."FORIGNEMBASSYMASTER" ("COUNTRYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMP_ADD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJ"."EMP_ADD_PK" ON "PROJ"."ADDRESSES" ("ADDRESSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PPT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJ"."PPT_PK" ON "PROJ"."PASSPORTS" ("PPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADDRESSES
--------------------------------------------------------

  ALTER TABLE "PROJ"."ADDRESSES" ADD CONSTRAINT "EMP_ADD_PK" PRIMARY KEY ("ADDRESSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENTMASTER
--------------------------------------------------------

  ALTER TABLE "PROJ"."DEPARTMENTMASTER" ADD CONSTRAINT "DEPT_ID_PK" PRIMARY KEY ("DEPARTMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COUNTRIES_MASTER
--------------------------------------------------------

  ALTER TABLE "PROJ"."COUNTRIES_MASTER" ADD CONSTRAINT "CNT_PK" PRIMARY KEY ("CNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJ"."COUNTRIES_MASTER" MODIFY ("CNT_NLTY" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."COUNTRIES_MASTER" MODIFY ("CNT_FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."COUNTRIES_MASTER" MODIFY ("CNT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEEMASTER
--------------------------------------------------------

  ALTER TABLE "PROJ"."EMPLOYEEMASTER" ADD UNIQUE ("LOGINID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PROJ"."EMPLOYEEMASTER" ADD CONSTRAINT "EMP_ID_PK" PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PROJ"."EMPLOYEEMASTER" MODIFY ("LOGINID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRAVELMASTER
--------------------------------------------------------

  ALTER TABLE "PROJ"."TRAVELMASTER" ADD PRIMARY KEY ("TRAVELID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PASSPORTS
--------------------------------------------------------

  ALTER TABLE "PROJ"."PASSPORTS" ADD CONSTRAINT "PPT_PK" PRIMARY KEY ("PPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJ"."PASSPORTS" MODIFY ("PPT_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."PASSPORTS" MODIFY ("PPT_ISSUE_PLACE" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."PASSPORTS" MODIFY ("PPT_EXPIRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."PASSPORTS" MODIFY ("PPT_ISSUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."PASSPORTS" MODIFY ("PPT_BIRTH_PLACE" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."PASSPORTS" MODIFY ("PPT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."PASSPORTS" MODIFY ("PPT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."PASSPORTS" MODIFY ("CNT_PPT_FK" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."PASSPORTS" MODIFY ("EMP_PPT_FK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VISA_TYPES
--------------------------------------------------------

  ALTER TABLE "PROJ"."VISA_TYPES" MODIFY ("VT_REQUIRED_ADV" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."VISA_TYPES" ADD CONSTRAINT "VT_PK" PRIMARY KEY ("VT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJ"."VISA_TYPES" MODIFY ("VT_ABBR" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."VISA_TYPES" MODIFY ("VT_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."VISA_TYPES" MODIFY ("CNT_VT_FK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOTELMASTER
--------------------------------------------------------

  ALTER TABLE "PROJ"."HOTELMASTER" ADD PRIMARY KEY ("HOTELID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TICKETSMASTER
--------------------------------------------------------

  ALTER TABLE "PROJ"."TICKETSMASTER" ADD PRIMARY KEY ("TICKETID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKS
--------------------------------------------------------

  ALTER TABLE "PROJ"."WORKS" ADD PRIMARY KEY ("WORK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORIGNEMBASSYMASTER
--------------------------------------------------------

  ALTER TABLE "PROJ"."FORIGNEMBASSYMASTER" MODIFY ("COUNTRYID" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."FORIGNEMBASSYMASTER" MODIFY ("EMBASSYADDRESS" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."FORIGNEMBASSYMASTER" MODIFY ("EMBASSYNAME" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."FORIGNEMBASSYMASTER" ADD CONSTRAINT "EMBASSY_CID_UK" UNIQUE ("COUNTRYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJ"."FORIGNEMBASSYMASTER" ADD PRIMARY KEY ("EMBASSYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMP_VISAS
--------------------------------------------------------

  ALTER TABLE "PROJ"."EMP_VISAS" MODIFY ("EV_COST" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."EMP_VISAS" ADD CONSTRAINT "EV_PK" PRIMARY KEY ("EV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJ"."EMP_VISAS" MODIFY ("EV_PLACE_OF_ISSUE" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."EMP_VISAS" MODIFY ("EV_MAX_VISITS" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."EMP_VISAS" MODIFY ("EV_EXPIRE_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."EMP_VISAS" MODIFY ("EV_ISSUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."EMP_VISAS" MODIFY ("EV_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "PROJ"."EMP_VISAS" MODIFY ("PPT_EV_FK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEESSTAYMASTER
--------------------------------------------------------

  ALTER TABLE "PROJ"."EMPLOYEESSTAYMASTER" ADD CONSTRAINT "EMP_STAY_TID" UNIQUE ("TRAVELID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJ"."EMPLOYEESSTAYMASTER" ADD PRIMARY KEY ("STAYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
